# Generated by Django 2.2.1 on 2019-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190529_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(default='Python,C++', max_length=50),
            preserve_default=False,
        ),
    ]
