# Generated by Django 2.2.1 on 2019-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_certificate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='summary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
