# Generated by Django 2.2.3 on 2019-08-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_githuburl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='githuburl',
        ),
        migrations.AddField(
            model_name='project',
            name='chk',
            field=models.ImageField(default='hello', upload_to='images/'),
            preserve_default=False,
        ),
    ]
