# Generated by Django 2.2.3 on 2019-08-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190810_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chk',
        ),
        migrations.AddField(
            model_name='project',
            name='githuburl',
            field=models.CharField(default='http://google.com/', max_length=200),
            preserve_default=False,
        ),
    ]
